spring:
  application:
    name: mortgage-checker

  port: 8080

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:mortgagecheckerdb
    username: sa

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

custom:
    config:
      incomeMultiplier: 4
