INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (101, 1.15, 1, now());
INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (102, 3.75, 2, now());
INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (103, 7.5, 3, now());
INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (104, 5, 5, now());
INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (105, 4.25, 10, now());
INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (106, 6.5, 15, now());
INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (107, 6.0, 20, now());
INSERT INTO INTEREST_RATES (ID,INTEREST_RATE, MATURITY_PERIOD, LAST_UPDATE) VALUES (108, 5.5, 30, now());
